server:
  port: 8080
  error:
    include-message: always

spring:
  application:
    name: spring-boot-test

  datasource:
    url: jdbc:mysql://localhost:3306/db_spring_boot_production
    username: admin
    password: magadiflo

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG